name: Python Tests & Linting

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/python.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
    
    # Temporarily comment out linting to focus on running tests
    # - name: Run linting
    #   run: |
    #     flake8 .
    #     pylint --disable=C0111,C0103,C0303,W1201,W1202,C0302,W0511,R0913,R0914 $(find . -type f -name "*.py" ! -path "./venv/*" ! -path "./.conda/*")
    
    - name: Run tests with pytest
      run: |
        # Run tests with better error handling
        python -m pytest tests/ -v
    
    - name: Generate coverage report
      run: |
        python -m pytest --cov=. --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 